FROM python:3.10-slim
# Cài đặt các dependency
RUN apt-get update && apt-get install -y \
    python3-pip && \
    pip install --no-cache-dir kafka-python websocket-client

# Copy mã nguồn
WORKDIR /app
COPY finnhub_producer.py /app/
COPY config.py /app/

# Run producer
CMD ["python", "finnhub_producer.py"]
